name: sync data and generate svg

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 16 * * *'  # 每天北京时间 08:00 执行一次

env:
  # change env here
  GITHUB_NAME: wansho
  GITHUB_EMAIL: wanshojs@gmail.com
  STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
  STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
  STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  sync:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if: steps.pip-cache.outputs.cache-hit != 'true'
      - name: sync data
        run: |
          python sync.py
      - name: generate svg
        run: |
          python render.py
      - name: commit
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add data/*.csv *.svg || true
          git commit -a -m 'sync and generate svg' || echo "nothing to commit"
          git push https://x-access-token:${PAT_TOKEN}@github.com/wansho/running.git HEAD:main || echo "nothing to push"
